# Success
GET http://localhost:8000/weather/01001000 HTTP/1.1
Host: localhost:8000
Content-Type: application/json

###

# Error: can not find zipcode
GET http://localhost:8000/weather/01153001 HTTP/1.1
Host: localhost:8000
Content-Type: application/json

###

# Error: invalid zipcode
GET http://localhost:8000/weather/0000000000 HTTP/1.1
Host: localhost:8000
Content-Type: application/json
